### ISSUE TITLE
4.2.1 Implict grant does not verify client Redirect URI

### ISSUE THREAD

**Issue by Licenser** [IvanMartinez/oauth2_webmachine#2]
I'm implementing a OAuth2 endpoint based on kivra oath2 your project is wonderful to work alongside the RFC and the kivra code.

Reading the both alongside I noticed that for the implicit grant (4.2.1) the RFC requires the client redirect URI to be authenticated however it seems you just check for the username and password authorize_password/2 it seems  authorize_password/5 seems to be the more appropriate?

**Comment by Licenser** [comment]
for the record it's 4th paragraph (not counting the list of parameters) on page 34.

**Comment by IvanMartinez** [comment]
Thank you for interest and feedback.
I couldn't find where the spec requires the redirect URI to be authenticated in the Implicit Grant flow, and I don't know how that is possible if the client is not authenticated either.
The flow is implemented by authorization_token.erl and it uses oauth2:authorize_password/5 of IvanMartinez/oauth2 in line 119.

**Comment by Licenser** [comment]
From RFC 6749 (4.2.1 p34)

The authorization server validates the request to ensure that all required parameters are present and valid. **The authorization server MUST verify that the redirection URI** to which it will redirect the access token matches the redirection URI registered by the client as described in Section 3.1.2.

I think the correct method to use would be: https://github.com/kivra/oauth2/blob/624392a3825a7169b504ad463c2b4a55c46a4d43/src/oauth2.erl#L112

which includes the URI and the Client passed is only the ClientID not a ID/Password pair.

This is how I ended up implementing 4.2:

https://github.com/project-fifo/wiggle/blob/59c85102605c07aec8a2f4d86b608bc54299ab49/apps/wiggle/src/wiggle_oauth_auth.erl#L170
